import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";

const Home: NextPage = () => {
  const session = useSession();
  const router = useRouter();
  if (!!session.data) {
    router.push("/dashboard");
  }
  return (
    <>
      <Head>
        <title>kindMind</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <span className="m-auto">Home</span>
      </>
    </>
  );
};

export default Home;
